### ISSUE TITLE
When using BOSH_ALL_PROXY and SSH key does not match, no error is generated

### ISSUE THREAD

**Issue by rob-greene** [cloudfoundry-incubator/bosh-backup-and-restore#25] opened 2018-12-20 15:44 UTC
We have been using `BOSH_ALL_PROXY` in our Concourse pipelines for BBR backups of our Bosh manifests. If the SSH key is rolled and the pipeline is not updated, BBR will not error out. It will simply hang until the process is killed.  This is difficult to diagnose.  A more appropriate behavior would be to error out with a appropriate error message.

**Comment by glestaris** [comment] 2019-01-04 15:36
Hey @rob-greene, does the BOSH CLI have the same behaviour in this scenario? BBR uses the BOSH CLI libraries for `BOSH_ALL_PROXY` support.

**Comment by rob-greene** [comment] 2019-01-07 21:30
Good catch. Yes, when I set `BOSH_ALL_PROXY` with the old key, it doesn't generate an error. I gave it about 5 minutes before terminating. As verification, I pulled the new key and that worked. Switched back to the old key and it hung.

**Comment by jamesjoshuahill** [comment] 2019-01-08 14:43
Hi @rob-greene, thank you for raising this issue. We have identified the root cause in the socks5-proxy package. See https://github.com/cloudfoundry/socks5-proxy/pull/13 for the fix.

We will keep this issue open to track progress. Once the `socks5-proxy` issue is resolved, we will need to bump the version in `bosh-utils` and `bosh-cli` and finally in BBR.

**Comment by jamesjoshuahill** [comment] 2019-02-01 13:51
`socks5-proxy` v0.1.0 has a fix for this issue.

A pull request has been opened to bump this dependency in `bosh-utils`: https://github.com/cloudfoundry/bosh-utils/pull/67.

**Comment by jamesjoshuahill** [comment] 2019-02-07 10:31
The `bosh-utils` PR has been merged: https://github.com/cloudfoundry/bosh-utils/pull/67

**Comment by terminatingcode** [comment] 2019-06-13 09:27
This issue is fixed in bbr [1.5.1](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/tag/v1.5.1)

**Closed** 2019-06-13 09:26 UTC
Labels: accepted
